syntax highlighting expanded

diff --git a/practice-manager/practice-manager b/practice-manager/practice-manager
--- a/practice-manager/practice-manager
+++ b/practice-manager/practice-manager
@@ -3,7 +3,12 @@
 main_configuration=\
 "## Language name for syntax highlighting
 ## Only specify names supported by prism.js
-## e.g. c cpp java python bash
+## List of supported syntaxes:
+### bash c cpp asm6502 java python aspnet csharp cmake django dns-zone docker
+### go hcl ignore javadoc json json5 kotlin latex makefile markdown matlab
+### mongodb nasm nginx objectivec opencl perl php phpdoc plsql powershell
+### processing prolog qml r regex ruby rust scala sql swift typescript
+### verilog vhdl vim wasm
 #LANGUAGE=
 
 ## Whether source can be executed either as compiled source or interpretable
@@ -433,8 +438,10 @@ function generate_html_body {
 		cat << EOF >> "./html-files/${index}.html"
 <body class="container">
 EOF
-	else
-		cat << EOF >> "./html-files/${index}.html"
+		return
+	fi
+
+	cat << EOF >> "./html-files/${index}.html"
 <!-- jquery -->
 <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
 <!-- bootstrap -->
@@ -443,13 +450,156 @@ EOF
 <!-- prism js -->
 <script src='https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/prism.min.js'></script>
 <!-- prism languages -->
-<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-c.min.js"></script>
-<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-clike.min.js"></script>
-<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-asm6502.min.js"></script>
-<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-cpp.min.js"></script>
-<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-java.min.js"></script>
-<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-python.min.js"></script>
-<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-bash.min.js"></script>
+EOF
+
+#echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-clike.min.js"></script>' >> "./html-files/${index}.html"
+	case "${LANGUAGE:-}" in
+		c)
+			echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-c.min.js"></script>' >> "./html-files/${index}.html"
+		;;
+		cpp|cxx|cplusplus)
+			echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-cpp.min.js"></script>' >> "./html-files/${index}.html"
+		;;
+		asm6502|asm|s|assembly)
+			echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-asm6502.min.js"></script>' >> "./html-files/${index}.html"
+		;;
+		java)
+			echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-java.min.js"></script>' >> "./html-files/${index}.html"
+		;;
+		python|py)
+			echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-python.min.js"></script>' >> "./html-files/${index}.html"
+		;;
+		aspnet)
+			echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-aspnet.min.js"></script>' >> "./html-files/${index}.html"
+		;;
+		csharp|cs|dotnet)
+			echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-csharp.min.js"></script>' >> "./html-files/${index}.html"
+		;;
+		cmake)
+			echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-cmake.min.js"></script>' >> "./html-files/${index}.html"
+		;;
+		django|jinja|jinja2)
+			echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-django.min.js"></script>' >> "./html-files/${index}.html"
+		;;
+		dns-zone-file|dns-zone)
+			echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-dns-zone.min.js"></script>' >> "./html-files/${index}.html"
+		;;
+		docker|dockerfile)
+			echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-docker.min.js"></script>' >> "./html-files/${index}.html"
+		;;
+		go)
+			echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-go.min.js"></script>' >> "./html-files/${index}.html"
+		;;
+		hcl)
+			echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-hcl.min.js"></script>' >> "./html-files/${index}.html"
+		;;
+		ignore|gitignore|hgignore|npmignore)
+			echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-ignore.min.js"></script>' >> "./html-files/${index}.html"
+		;;
+		javadoc)
+			echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-javadoc.min.js"></script>' >> "./html-files/${index}.html"
+		;;
+		json)
+			echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-json.min.js"></script>' >> "./html-files/${index}.html"
+		;;
+		json5)
+			echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-json5.min.js"></script>' >> "./html-files/${index}.html"
+		;;
+		kotlin|kt|kts)
+			echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-kotlin.min.js"></script>' >> "./html-files/${index}.html"
+		;;
+		atex|tex|context)
+			echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-latex.min.js"></script>' >> "./html-files/${index}.html"
+		;;
+		makefile)
+			echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-makefile.min.js"></script>' >> "./html-files/${index}.html"
+		;;
+		md|markdown)
+			echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-markdown.min.js"></script>' >> "./html-files/${index}.html"
+		;;
+		octave|matlab)
+			echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-matlab.min.js"></script>' >> "./html-files/${index}.html"
+		;;
+		mongodb)
+			echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-mongodb.min.js"></script>' >> "./html-files/${index}.html"
+		;;
+		nasm)
+			echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-nasm.min.js"></script>' >> "./html-files/${index}.html"
+		;;
+		nginx)
+			echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-nginx.min.js"></script>' >> "./html-files/${index}.html"
+		;;
+		objectivec|objc)
+			echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-objectivec.min.js"></script>' >> "./html-files/${index}.html"
+		;;
+		opencl)
+			echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-opencl.min.js"></script>' >> "./html-files/${index}.html"
+		;;
+		perl)
+			echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-perl.min.js"></script>' >> "./html-files/${index}.html"
+		;;
+		php)
+			echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-php.min.js"></script>' >> "./html-files/${index}.html"
+		;;
+		phpdoc)
+			echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-phpdoc.min.js"></script>' >> "./html-files/${index}.html"
+		;;
+		plsql)
+			echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-plsql.min.js"></script>' >> "./html-files/${index}.html"
+		;;
+		powershell)
+			echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-powershell.min.js"></script>' >> "./html-files/${index}.html"
+		;;
+		processing)
+			echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-processing.min.js"></script>' >> "./html-files/${index}.html"
+		;;
+		prolog)
+			echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-prolog.min.js"></script>' >> "./html-files/${index}.html"
+		;;
+		qml)
+			echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-qml.min.js"></script>' >> "./html-files/${index}.html"
+		;;
+		r)
+			echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-r.min.js"></script>' >> "./html-files/${index}.html"
+		;;
+		regex)
+			echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-regex.min.js"></script>' >> "./html-files/${index}.html"
+		;;
+		ruby|rb)
+			echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-ruby.min.js"></script>' >> "./html-files/${index}.html"
+		;;
+		rust)
+			echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-rust.min.js"></script>' >> "./html-files/${index}.html"
+		;;
+		scala)
+			echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-scala.min.js"></script>' >> "./html-files/${index}.html"
+		;;
+		sql)
+			echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-sql.min.js"></script>' >> "./html-files/${index}.html"
+		;;
+		swift)
+			echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-swift.min.js"></script>' >> "./html-files/${index}.html"
+		;;
+		typescript|ts)
+			echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-typescript.min.js"></script>' >> "./html-files/${index}.html"
+		;;
+		verilog)
+			echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-verilog.min.js"></script>' >> "./html-files/${index}.html"
+		;;
+		vhdl)
+			echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-vhdl.min.js"></script>' >> "./html-files/${index}.html"
+		;;
+		vim)
+			echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-vim.min.js"></script>' >> "./html-files/${index}.html"
+		;;
+		wasm)
+			echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-wasm.min.js"></script>' >> "./html-files/${index}.html"
+		;;
+	esac
+
+	echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-bash.min.js"></script>' >> "./html-files/${index}.html"
+
+	cat << EOF >> "./html-files/${index}.html"
 <!-- prism plugins -->
 <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/plugins/toolbar/prism-toolbar.min.js"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/plugins/autolinker/prism-autolinker.min.js"></script>
@@ -458,9 +608,9 @@ EOF
 <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/plugins/normalize-whitespace/prism-normalize-whitespace.min.js"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/plugins/remove-initial-line-feed/prism-remove-initial-line-feed.min.js"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/plugins/show-language/prism-show-language.min.js"></script>
-</body>
 EOF
-	fi
+
+	echo '</body>' >> "./html-files/${index}.html"
 }
 
 # requires path to page
@@ -1093,11 +1243,11 @@ function compile_source {
 					echo "  command: $execution_command" >&2
 					tput sgr0
 				fi
+			fi
 
-				if [ "${GENERATES_COMPILATION_ERROR:-false}" != "true" ] || [ "$(wc -w < "$compilation_error")" -eq 0 ]
-				then
-					rm "$compilation_error"
-				fi
+			if [ "${GENERATES_COMPILATION_ERROR:-false}" != "true" ] || [ "$(wc -w < "$compilation_error")" -eq 0 ]
+			then
+				rm "$compilation_error"
 			fi
 		elif [ "${LINKABLE:-false}" = "true" ]
 		then
@@ -1153,11 +1303,11 @@ function compile_source {
 					echo "  command: $execution_command" >&2
 					tput sgr0
 				fi
+			fi
 
-				if [ "${GENERATES_LINKAGE_ERROR:-false}" != "true" ] || [ "$(wc -w < "$linkage_error")" -eq 0 ]
-				then
-					rm "$linkage_error"
-				fi
+			if [ "${GENERATES_LINKAGE_ERROR:-false}" != "true" ] || [ "$(wc -w < "$linkage_error")" -eq 0 ]
+			then
+				rm "$linkage_error"
 			fi
 		elif [ "${LINKABLE:-false}" = "true" ] && [ -z "$LINKER" ]
 		then
@@ -1403,20 +1553,27 @@ function run_program {
 						echo "  command: $running_command" >&2
 						tput sgr0
 					fi
-
-					# remove empty or unwanted error files
-					if [ "${GENERATES_RUNTIME_ERROR:-false}" != "true" ] || [ "$(wc -w < "$runtime_error")" -eq 0 ]
-					then
-						rm "$runtime_error"
-					fi
+				fi
+				# remove empty or unwanted error files
+				if [ "${GENERATES_RUNTIME_ERROR:-false}" != "true" ] || [ "$(wc -w < "$runtime_error")" -eq 0 ]
+				then
+					rm "$runtime_error"
 				fi
 			else
 				if ! $running_command 2> "$runtime_error" 1> "$output"
 				then
-					tput bold
-					echo "running program failed: $source" >&2
-					echo "  command: $running_command" >&2
-					tput sgr0
+					if [ "${GENERATES_RUNTIME_ERROR:-false}" != "true" ]
+					then
+						tput bold
+						echo "running program failed: $source" >&2
+						echo "  command: $running_command" >&2
+						tput sgr0
+					fi
+				fi
+				# remove empty or unwanted error files
+				if [ "${GENERATES_RUNTIME_ERROR:-false}" != "true" ] || [ "$(wc -w < "$runtime_error")" -eq 0 ]
+				then
+					rm "$runtime_error"
 				fi
 			fi
 		fi
@@ -2675,7 +2832,7 @@ function analyze_paramters {
 
 if [ -f ./.config ] && [ ./.index ]
 then
-	validation_check=202012131613
+	validation_check=202012182136
 	source ./.config
 	if [ "${VALIDATION_ID:-0}" -lt "$validation_check" ]
 	then
