index_page, nearest_path and deepest_path functions added to practice-manager

diff --git a/practice-manager/practice-manager b/practice-manager/practice-manager
--- a/practice-manager/practice-manager
+++ b/practice-manager/practice-manager
@@ -1,5 +1,8 @@
 #!/usr/bin/env bash
 
+# required functions
+###############################################################################
+
 ## description: outputs string with style and color
 ## usage: show [%style%/%color%] [string] ... [string]
 ## style list:
@@ -119,147 +122,8 @@ function usage {
 	exit 0
 }
 
-# requires absolute path to source to configure corresponding variables
-function update_configuration {
-	local directory
-	local config
-
-	for level in ${1//\//$'\n'}
-	do
-		if [ -d "$directory$level" ]
-		then
-			directory="$directory$level/"
-		elif [ -f "$directory$level" ]
-		then
-			directory="$directory${level%.*}"
-		fi
-
-		config="$directory.config"
-
-		if [ -f "$config" ]
-		then
-			source "$config"
-		fi
-	done
-}
-
-function generate_execution_section {
-	echo "  <h2>Execution</h2>" >> "./html-files/${index}.html"
-}
-
-# requires path to page
-# requires compile/link/run option
-# requires command
-function generate_execution_mode {
-	local page="${1}"
-	local mode="${2:-compile}"
-	local command="${3}"
-
-	if [ -z "$command" ]
-	then
-		tput bold
-		echo "execution command not specified: $page"
-		tput sgr0
-		return 1
-	fi
-
-	echo "  <h4>${mode}</h4>"  >> "./html-files/${index}.html"
-	echo "   <p class=\"command-style\">${command}</p>" >> "./html-files/${index}.html"
-}
-
-# requires absolute path to source
-function compile_source {
-	update_configuration "$1"
-
-	if [ "$EXECUTABLE" != "true" ]
-	then
-		return 2
-	fi
-
-	generate_execution_section "$1"
-
-	local binary="${1%.*}.bin"
-	local object="${1%.*}.o"
-	local output="${1%.*}.output.txt"
-	local execution_command
-	local output_change_time
-	local source_change_time
-
-	if [ "$COMPILABLE" = "true" ] && [ -z "$COMPILER" ]
-	then
-		echo "$COMPILABLE $COMPILER"
-		tput bold
-		echo "compiler not specified for: $1" >&2
-		tput sgr0
-		return 1
-	fi
-
-	source_change_time=$(stat -c "%Y" "$1")
-
-	if [ -f "$output" ]
-	then
-		output_change_time=$(stat -c "%Y" "$output")
-	else
-		output_change_time=0
-	fi
-
-	if ! [ -f "$output" ] || [ "$source_change_time" -gt "$output_change_time" ]
-	then
-		if [ "$COMPILABLE" = "true" ]
-		then
-			execution_command="$COMPILER $COMPILER_OPTIONS $object $1"
-			if ! $execution_command
-			then
-				tput bold
-				echo "compilation error: $1" >&2
-				tput sgr0
-				return 1
-			fi
-		else
-			execution_command="$COMPILER $COMPILER_OPTIONS $1"
-			if [ -f "$binary" ]
-			then
-				unlink "$binary"
-			fi
-			ln -s "$PWD/$1" "$binary"
-		fi
-		generate_execution_mode "$1" compile "$execution_command"
-	else
-		if [ "$COMPILABLE" = "true" ]
-		then
-			execution_command="$COMPILER $COMPILER_OPTIONS ${object##*/} ${1##*/}"
-			generate_execution_mode "$1" compile "$execution_command"
-		else
-			execution_command="$COMPILER $COMPILER_OPTIONS ${1##*/}"
-			generate_execution_mode "$1" compile "$execution_command"
-		fi
-	fi
-
-	execution_command="$LINKER $LINKER_OPTIONS $binary $object"
-
-	if ! [ -f "$output" ] || [ "$source_change_time" -gt "$output_change_time" ]
-	then
-		if [ "$COMPILABLE" = "true" ] && [ -n "$LINKER" ]
-		then
-			if ! $execution_command
-			then
-				tput bold
-				echo "linkage error for: $1" >&2
-				tput sgr0
-				return 1
-			fi
-		elif [ "$COMPILABLE" = "true" ] && [ -z "$LINKER" ]
-		then
-			tput bold
-			echo "linker not specified for: $1" >&2
-			tput sgr0
-			return 1
-		fi
-	fi
-
-	execution_command="$LINKER $LINKER_OPTIONS ${binary##*/} ${object##*/}"
-	generate_execution_mode "$1" link "$execution_command"
-}
+# html line generators
+###############################################################################
 
 # requires path to page
 # requires begin/end as second parameter
@@ -388,6 +252,7 @@ EOF
 }
 
 # requires path to page
+# optional begin/end
 # optional css style name
 function generate_html_div {
 	local page="${1%.*}"
@@ -428,78 +293,324 @@ function generate_html_link {
 }
 
 # requires path to page
-# optional minimum depth as second parameter
-# returns 0 if successfully indexed to depth, and greater than 0 on error
-function index_page {
-	local page="${1%.*}"
-	page="${page##*/}"
-	local depth=0
-	local min_depth="${2:-1}"
-	local entry
-	local hierarchy
-	# FIXME: index should not be global
-	index=
-	local match
-	local digit_pad
+# requies text
+# optional command
+function generate_html_text {
+	local page="$1"
+	local text="$2"
+	local style="$3"
+	local tag=
 
-	for entry in ${1//\//$'\n'}
+	if [ -n "$style" ]
+	then
+		tag="<p class=\"${style}\">"
+	else
+		tag="<p>"
+	fi
+
+	echo "   ${tag}${text}</p>" >> "./html-files/${index}.html"
+}
+
+# required functions for managing practice pages
+###############################################################################
+
+# requires absolute path to source to configure corresponding variables
+function update_configuration {
+	local directory
+	local config
+
+	for level in ${1//\//$'\n'}
 	do
-		if [ -n "$hierarchy" ]
+		if [ -d "$directory$level" ]
 		then
-			hierarchy="${hierarchy}/${entry}"
-		else
-			hierarchy="$entry"
+			directory="$directory$level/"
+		elif [ -f "$directory$level" ]
+		then
+			directory="$directory${level%.*}"
 		fi
 
-		if [ "$depth" -lt "$min_depth" ]
-		then
-			((depth++))
-			continue
-		fi
+		config="$directory.config"
 
-		if [ -d "$hierarchy" ]
+		if [ -f "$config" ]
 		then
-			if ! [ -f "${hierarchy}/.index" ]
+			source "$config"
+		fi
+	done
+}
+
+# requires path to page
+# requires compile/link/run option
+# requires command
+function generate_execution_mode {
+	local page="${1}"
+	local mode="${2:-compile}"
+	local command="${3}"
+
+	if [ -z "$command" ]
+	then
+		tput bold
+		echo "execution command not specified: $page"
+		tput sgr0
+		return 1
+	fi
+
+	generate_html_header "$1" 4 "${mode}"
+	generate_html_text "$1" "$command" command-style
+}
+
+# requires absolute path to source
+# option headers and required files
+function compile_source {
+	update_configuration "$1"
+
+	if [ "$EXECUTABLE" != "true" ]
+	then
+		return 2
+	fi
+
+	generate_html_header "$1" 2 "Execution"
+
+	local binary="${1%.*}.bin"
+	local object="${1%.*}.o"
+	local headers="$@"
+	headers="${headers/$1 }"
+	local includes=
+	local output="${1%.*}.output.txt"
+	local execution_command
+	local output_change_time
+	local source_change_time
+
+	if [ "$COMPILABLE" = "true" ] && [ -z "$COMPILER" ]
+	then
+		echo "$COMPILABLE $COMPILER"
+		tput bold
+		echo "compiler not specified for: $1" >&2
+		tput sgr0
+		return 1
+	fi
+
+	if [ "$INCLUDES" != "true" ]
+	then
+		headers=
+	fi
+
+	source_change_time=$(stat -c "%Y" "$1")
+
+	if [ -f "$output" ]
+	then
+		output_change_time=$(stat -c "%Y" "$output")
+	else
+		output_change_time=0
+	fi
+
+	if ! [ -f "$output" ] || [ "$source_change_time" -ge "$output_change_time" ]
+	then
+		if [ "$COMPILABLE" = "true" ]
+		then
+			execution_command="$COMPILER $COMPILER_OPTIONS $object $1"
+			echo "compile: $execution_command"
+			if ! $execution_command
 			then
 				tput bold
-				echo "hierarchy not indexed: $hierarchy" >&2
+				echo "compilation error: $1" >&2
 				tput sgr0
 				return 1
 			fi
-		elif [ -f "$hierarchy" ]
-		then
-			if [ "$entry" = "README.md" ]
+		else
+			execution_command="$COMPILER $COMPILER_OPTIONS $object"
+			if [ -f "$binary" ]
 			then
-				index="${index}${digit_pad}0."
-				break
+				unlink "$binary"
 			fi
+			ln -s "$PWD/$1" "$binary"
+		fi
+		generate_execution_mode "$1" compile "$execution_command"
+	else
+		if [ "$COMPILABLE" = "true" ]
+		then
+			execution_command="$COMPILER $COMPILER_OPTIONS ${object##*/} ${1##*/}"
+			generate_execution_mode "$1" compile "$execution_command"
+		else
+			execution_command="$COMPILER $COMPILER_OPTIONS ${1##*/}"
+			generate_execution_mode "$1" compile "$execution_command"
+		fi
+	fi
 
-			if [ "$(grep -c "$entry" "${hierarchy%/*}/.index")" -ne 1 ]
+	execution_command="$LINKER $LINKER_OPTIONS $binary $object $headers"
+
+	if ! [ -f "$output" ] || [ "$source_change_time" -ge "$output_change_time" ]
+	then
+		if [ "$COMPILABLE" = "true" ] && [ -n "$LINKER" ]
+		then
+			echo "link: $execution_command"
+			if ! $execution_command
 			then
 				tput bold
-				echo "page not indexed in hierarchy: $hierarchy" >&2
+				echo "linkage error for: $1" >&2
 				tput sgr0
-				return 3
+				return 1
 			fi
-		else
-			tput bold
-			echo "broken hierarchy: $hierarchy" >&2
-			tput sgr0
-			return 4
-		fi
-
-		match="$(grep -n "$entry" "${hierarchy%/*}/.index")"
-		match="${match%%:*}"
-		if [ "${#match}" -eq 1 ]
+		elif [ "$COMPILABLE" = "true" ] && [ -z "$LINKER" ]
 		then
-			match="${digit_pad}${match}"
+			tput bold
+			echo "linker not specified for: $1" >&2
+			tput sgr0
+			return 1
 		fi
-		index="${index}${match}."
-		((depth++))
+	fi
+
+	binary="${binary##*/}"
+	object="${object##*/}"
+	for header in $headers
+	do
+		includes+="$header "
 	done
 
-	index="${index%.}"
+	execution_command="$LINKER $LINKER_OPTIONS $binary $object $includes"
+	generate_execution_mode "$1" link "$execution_command"
 }
+
+# requires path to page
+# optional floor to start indexing directories
+# sets page_index and page_hierarchy variables
+function index_page {
+	local floor="${2:-1}"
+
+	local depth=1
+	local entry=
+	local hierarchy=
+	local index=
+	page_index=
+	page_hierarchy=
+
+	for entry in ${1//\//$'\n'}
+	do
+		hierarchy="${hierarchy:-$entry}"
+
+		if [ "$depth" -gt "$floor" ]
+		then
+			match="$(grep -n "$entry" "${hierarchy}/.index")"
+			match="${match%%:*}"
+			match="${match%% *}"
+			((match--)) # shift index down because of readme indexes
+			index+="${match}."
+		fi
+
+		((depth++))
+		hierarchy="${hierarchy}/${entry}"
+	done
+	page_index="${index%.}"
+	page_hierarchy="$hierarchy"
+}
+
+# requires path to page
+# optional up/down for direction of growth
+# sets deepest_page variable
+function deepest_path {
+	local hierarchy="${1%/}"
+	local direction="${2:-up}"
+
+	local entry=
+	local tool=
+	deepest_page=
+
+	if [ "$direction" = "up" ]
+	then
+		tool="head"
+	elif [ "$direction" = "down" ]
+	then
+		tool="tail"
+	else
+		return 1
+	fi
+
+	while true
+	do
+		if [ -d "$hierarchy" ] && [ -f "${hierarchy}/.index" ]
+		then
+			entry="$("$tool" -n1 "${hierarchy}/.index")"
+			entry="${entry%% *}"
+			if [ -n "$entry" ]
+			then
+				hierarchy="${hierarchy}/${entry}"
+			else
+				break
+			fi
+		else
+			break
+		fi
+	done
+	deepest_page="$hierarchy"
+}
+
+# requires path to page
+# optional up/down for direction of growth
+# sets page_index and page_hierarchy variables
+# note: empty variables means there is no neighbor
+function nearest_path {
+	local hierarchy="${1%/}"
+	local page="${hierarchy##*/}"
+	hierarchy="${hierarchy%/*}"
+	local direction="${2:-up}"
+	local match=
+	local option=
+
+	if [ "$direction" = "up" ]
+	then
+		option="-B1"
+	elif [ "$direction" = "down" ]
+	then
+		option="-A1"
+	else
+		return 1
+	fi
+
+	while [ "$hierarchy" != "." ]
+	do
+		match="$(grep "$option" "$page" "${hierarchy}/.index")"
+
+		if [ "$direction" = "up" ]
+		then
+			match="${match%$'\n'*}"
+		else
+			match="${match#*$'\n'}"
+		fi
+		match="${match%% *}"
+
+		if [ "$match" = "$page" ]
+		then
+			page="${hierarchy##*/}"
+			hierarchy="${hierarchy%/*}"
+		else
+			if [ "$direction" = "up" ]
+			then
+				direction="down"
+			else
+				direction="up"
+			fi
+
+			if [ -d "${hierarchy}/${match}" ]
+			then
+				deepest_path "${hierarchy}/${match}" "$direction"
+				page="$deepest_page"
+			else
+				page="${hierarchy}/${match}"
+			fi
+
+			index_page "$page"
+			break
+		fi
+	done
+
+	if [ "$hierarchy" = "." ]
+	then
+		page_index=
+		page_hierarchy=
+	fi
+}
+
+# functions to generate html pages
+###############################################################################
 
 function generate_index_section {
 	local tag="<h1>"
@@ -575,7 +686,7 @@ function generate_output_section {
 	local input="$page.input.txt"
 	page="${page##*/}"
 
-	if ! compile_source "$1"
+	if ! compile_source $@
 	then
 		return 1
 	fi
@@ -679,11 +790,21 @@ function generate_toc_section {
 	local page="${1%.*}"
 	page="${page##*/}"
 
-	find_neighbor_index "$1"
 	generate_html_header "$1" 2 "Quick Access"
 	generate_html_div "$1" begin
-	generate_html_link "$1" "${previous_index}.html" "previous page"
-	generate_html_link "$1" "${next_index}" "next page"
+
+	nearest_path "$1" up
+	if [ -n "$page_index" ]
+	then
+		generate_html_link "$1" "${page_index}.html" "previous page"
+	fi
+
+	nearest_path "$1" down
+	if [ -n "$page_index" ]
+	then
+		generate_html_link "$1" "${page_index}.html" "next page"
+	fi
+
 	generate_html_div "$1" end
 }
 
@@ -700,9 +821,13 @@ function generate_index_page {
 	generate_html_section "$page" end
 }
 
+# functions to start the script working
+###############################################################################
+
 # requires path to page
 function generate_page {
 	index_page "$1"
+	index="$page_index"
 	generate_html_section "$1" begin
 	generate_html_head "$1" begin
 	generate_style "$1"
@@ -722,6 +847,7 @@ function generate_page {
 # requires absolute path to page
 function generate_chapter {
 	index_page "$1/README.md"
+	index="$page_index"
 	generate_html_section "$1/README.md" begin
 	generate_html_head "$1/README.md" begin
 	generate_style "$1/README.md"
@@ -734,32 +860,6 @@ function generate_chapter {
 	generate_html_body "$1/README.md" end
 	generate_html_section "$1/README.md" end
 	index=
-}
-
-# requires absolute path to page
-function generate_configuration {
-	local page
-
-	if [ -f "$1" ]
-	then
-		page="${1%.*}.config"
-	elif [ -d "$1" ]
-	then
-		page="${1%/}/.config"
-	fi
-
-	cat << EOF > "$page"
-COMPILER=
-COMPILER_OPTIONS=
-COMPILABLE=true
-LINKER=
-LINKER_OPTIONS=
-EXECUTABLE=true
-COMMENTS=true
-ADDITIONAL_EXTENSIONS="reference.txt comment.txt title.txt"
-# levels: amateur, intermediate, expert
-TECHNICAL_LEVEL=
-EOF
 }
 
 # requires relative path to list
@@ -798,6 +898,9 @@ function expand_list {
 				fi
 			done
 			generate_page $group
+		elif [ -f "$directory/$line" ] && [ "$line" = "README.md" ]
+		then
+			continue
 		elif [ -f "$directory/$line" ]
 		then
 			generate_page "$directory/$line"
@@ -827,6 +930,36 @@ function generate_manuals {
 	generate_index_page
 
 	expand_list "$1"
+}
+
+# functions for specific options
+###############################################################################
+
+# requires absolute path to page
+function generate_configuration {
+	local page
+
+	if [ -f "$1" ]
+	then
+		page="${1%.*}.config"
+	elif [ -d "$1" ]
+	then
+		page="${1%/}/.config"
+	fi
+
+	cat << EOF > "$page"
+COMPILER=
+COMPILER_OPTIONS=
+COMPILABLE=true
+LINKER=
+LINKER_OPTIONS=
+EXECUTABLE=true
+INCLUDES=false
+COMMENTS=true
+ADDITIONAL_EXTENSIONS="reference.txt comment.txt title.txt"
+# levels: amateur, intermediate, expert
+TECHNICAL_LEVEL=
+EOF
 }
 
 # requires path to location where practice will be added
@@ -980,19 +1113,22 @@ function move_chapter {
 
 function touch_sources {
 	find -type f -name ".index" -exec sh -c '
-		directory="{}";
-		while read -r file;
+		directory="{}"
+		while read -r file
 		do
-			filename="${directory%/*}/$file";
-			if [ -f "$filename" ];
-			then
-				touch "$filename";
-			fi;
-		done < {};' \;
+			for entry in $file
+			do
+				filename="${directory%/*}/$entry"
+				if [ -f "$filename" ]
+				then
+					touch "$filename"
+				fi
+			done
+		done < {}' \;
 }
 
-###############################################################################
 # Parameter Parser
+###############################################################################
 
 if [ $# -eq 0 ]
 then
