error section added to pages

diff --git a/practice-manager/practice-manager b/practice-manager/practice-manager
--- a/practice-manager/practice-manager
+++ b/practice-manager/practice-manager
@@ -48,6 +48,7 @@ main_configuration=\
 ## Wether generated output can run as an executable
 #RUNNABLE=true
 #RUNNING_OPTIONS=
+#GENERATES_ERROR=false
 
 ## Order of statements in running command
 ## Available statements: compiler, linker, options, binary, object, headers,
@@ -74,6 +75,7 @@ main_configuration=\
 #SOURCE=true
 #EXECUTION=true
 #OUTPUT=true
+#ERROR=true
 #INPUT=true
 #REFERENCE=true
 
@@ -1311,6 +1313,7 @@ function run_program {
 	local headers="$@"
 	headers="${headers/$1 }"
 	local output="${1%.*}.output.txt"
+	local error="${1%.*}.error.txt"
 	local location="${1%/*}"
 	local component=
 	local source_change_time=
@@ -1356,15 +1359,23 @@ function run_program {
 		then
 			if [ -f "$input" ]
 			then
-				if ! $running_command < "$input" > "$output"
+				if ! $running_command < "$input" 2> "$error" 1> "$output"
 				then
-					tput bold
-					echo "running program failed: $source" >&2
-					echo "  command: $running_command" >&2
-					tput sgr0
+					if [ "${GENERATES_ERROR:-false}" != "true" ]
+					then
+						tput bold
+						echo "running program failed: $source" >&2
+						echo "  command: $running_command" >&2
+						tput sgr0
+					fi
+					# remove empty or unwanted error files
+					if [ "${GENERATES_ERROR:-false}" != "true" ] || [ $(wc -w < "$error") -eq 0 ]
+					then
+						rm "$error"
+					fi
 				fi
 			else
-				if ! $running_command > "$output"
+				if ! $running_command 2> "$error" 1> "$output"
 				then
 					tput bold
 					echo "running program failed: $source" >&2
@@ -1510,6 +1521,7 @@ function generate_output_section {
 	local page="${1%.*}"
 	local binary="$page.bin"
 	local output="$page.output.txt"
+	local error="$page.error.txt"
 	local input="$page.input.txt"
 	page="${page##*/}"
 	local line
@@ -1561,6 +1573,34 @@ function generate_output_section {
 		else
 			tput bold
 			echo "output file not found: $output" >&2
+			tput sgr0
+		fi
+	fi
+
+	if [ "${ERROR:-false}" = "true" ]
+	then
+		if [ -f "$error" ]
+		then
+			if [ "$(wc -w < "$error")" -gt 0 ]
+			then
+				generate_html_header "$1" 3 Error
+				generate_html_code "$1" begin language-bash
+
+				while read -r line
+				do
+					echo "$line" >> "./html-files/${index}.html"
+				done < "$error"
+
+				if [ "$(wc -l < "$error")" -eq 0 ]
+				then
+					echo >> "$error"
+				fi
+
+				generate_html_code "$1" end
+			fi
+		else
+			tput bold
+			echo "error file wanted but not found: $error" >&2
 			tput sgr0
 		fi
 	fi
@@ -2509,7 +2549,7 @@ function analyze_paramters {
 
 if [ -f ./.config ] && [ ./.index ]
 then
-	validation_check=202012111751
+	validation_check=202012122128
 	source ./.config
 	if [ "${VALIDATION_ID:-0}" -lt "$validation_check" ]
 	then
@@ -2526,9 +2566,10 @@ then
 		sed -i "s/^\(VALIDATION_ID=\)[0-9]*$/\1${validation_check}/" ./.config
 		echo "Notes:"
 		echo
-		echo "    1. Practices belong to whom already know the topics"
-		echo "    2. Practices should cover easily forgotten details not basics"
-		echo "    3. Practices are meant to complement documentaions not be to a documentation itself"
+		echo "    1. practices are for whom have just begun learning a new skill"
+		echo "    2. practices should make reviewing newly learned skills possible, keep them as simple as possible"
+		echo "    3. practices are going to be used on a daily basis, keep them as short as possible"
+		echo "    4. practices should cover fundamental details not to be a comprehensive documentation"
 		echo
 		echo "configuration complete"
 		echo "run again to continue"
